### ISSUE TITLE
Wrong detection of C813

### ISSUE THREAD

**Issue by extsoft** [PyCQA/flake8-commas#55] opened 2018-12-14 19:50 UTC
There is the following code:
```python
print(
    'too long line'
    ' second part'
    ' last part'
     )
```

It uses https://docs.python.org/3/reference/lexical_analysis.html#string-literal-concatenation feature to split long lines. This code is correct based on regular flake8 checks.

But it raises `print.py:4:17: C813 missing trailing comma in Python 3` error. 

My expectation that it has to pass `flake8-commas` rules also, hasn't it?

**Comment by meshy** [comment] 2018-12-14 20:58
This is related to (possibly a duplicate of?) https://github.com/PyCQA/flake8-commas/pull/38

**Comment by extsoft** [comment] 2018-12-18 20:41
@graingert Could you please clary the logic for me?

[According to the code](https://github.com/PyCQA/flake8-commas/blob/8ec550f763404e17ed65ece4aeee743a9ee05a08/test/data/keyword_before_parenth_form/py2_3.py#L8), we need to have a comma for the case:

```python
print (
    "foo"
)
```

This means that if there is a multiline instead of `foo`, we need a comma also. Is it correct or not?

**Comment by graingert** [comment] 2019-06-17 12:12
Yes you need a comma here

**Closed by graingert** 2019-06-17 12:12 UTC
